unbind C-b
set -g prefix C-space
bind C-space send-prefix

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind C-h resize-pane -L 2
bind C-j resize-pane -D 2
bind C-k resize-pane -U 2
bind C-l resize-pane -R 2

unbind '"'
bind '"' split-pane -h -c "#{pane_current_path}"
unbind '%'
bind '%' split-pane -v -c "#{pane_current_path}"

bind f resize-pane -Z

bind c new-window -c "#{pane_current_path}"

bind x kill-pane

bind C-e display-popup \
    -w 75% \
    -h 75% \
    -E "tmux list-sessions | sed -E 's/:.*$//' | grep -v \"^$(tmux display-message -p '#S')\$\" | fzf --reverse | xargs tmux switch-client -t"

bind C-g display-popup \
    -w 95% \
    -h 95% \
    -d "#{pane_current_path}" \
    -E "lazygit"

bind C-y display-popup \
    -d "#{pane_current_path}" \
    -w 90% \
    -h 90% \
    -E "yazi"

unbind r
bind r source-file $HOME/.tmux.conf

set -g mouse on

set -g base-index 1
setw -g pane-base-index 1

set -g renumber-windows on

set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'b0o/tmux-autoreload'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'jimeh/tmuxifier'
set -g @plugin 'christoomey/vim-tmux-navigator'

# Configure Catppuccin
set -g @catppuccin_flavor "macchiato"
set -g @catppuccin_status_background "none"
set -g @catppuccin_window_status_style "none"
set -g @catppuccin_pane_status_enabled "off"
set -g @catppuccin_pane_border_status "off"

set -g @resurrect-strategy-vim 'session'
set -g @ressurect-capture-pane-contents 'on'
set -g @continuum-restore 'on'

run '$HOME/.tmux/plugins/tpm/tpm'

set -g status-position top
set -g status-justify "absolute-centre"
set -g status-style "bg=#{@thm_bg}"
set -g status-left ""
set -ga status-left "#[bold]#{?client_prefix,#[fg=#{@thm_mauve}],#{?#{==:#{pane_mode},copy-mode},#[fg=#{@thm_yellow}],#[fg=#{@thm_overlay_1}]}} #S "

set -g status-right ""
set -ga status-right "#[bold]#[fg=#{@thm_yellow}] %H:%M #[fg=#{@thm_overlay_1}]| "
set -ga status-right "#[fg=#{@thm_yellow}]%d-%m"

setw -g pane-border-lines single

set -g message-style 'bg=#{@thm_surface_2} fg=#{@thm_mauve} bold'

set -wg automatic-rename on
set -g automatic-rename-format "Window"

set -g window-status-separator "#[fg=#{@thm_overlay_1}]|"
set -g window-status-format '#[fg=#{@thm_overlay_1}] ⬤ #{?#{!=:#{window_name},Window},#W,}'
set -g window-status-current-format '#[fg=#{@thm_mauve},bg=default,bold] ⬤ #{?#{!=:#{window_name},Window},#W,}'

set -g pane-border-style "fg=#{@thm_surface_2}"
set -g pane-active-border-style "fg=#{@thm_mauve}"
