unbind C-b
set -g prefix C-space
bind C-space send-prefix

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind H resize-pane -L 2
bind J resize-pane -D 2
bind K resize-pane -U 2
bind L resize-pane -R 2

unbind '"'
bind '"' split-pane -h -c "#{pane_current_path}"
unbind '%'
bind '%' split-pane -v -c "#{pane_current_path}"

bind f resize-pane -Z

bind c new-window -c "#{pane_current_path}"

bind x kill-pane

bind C-n display-popup \
-w 75% \
-h 75% \
-E 'bash -c "read -p \"Session name: \" name; echo \$name; tmux new -d -s \$name; tmux switchc -t \$name"'

bind C-e display-popup \
-w 75% \
-h 75% \
-E "tmux list-sessions | sed -E 's/:.*$//' | grep -v \"^$(tmux display-message -p '#S')\$\" | fzf --reverse | xargs tmux switchc -t"

bind C-g display-popup \
-w 95% \
-h 95% \
-d "#{pane_current_path}" \
-E "lazygit"

bind C-y display-popup \
-d "#{pane_current_path}" \
-w 90% \
-h 90% \
-E "yazi"

unbind r
bind r { source $HOME/.tmux.conf; display "Reloaded .tmux.conf" }

set -g mouse on

set -g base-index 1
setw -g pane-base-index 1

set -g renumber-windows on

set -g display-time 1000
set -g escape-time 0

set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'b0o/tmux-autoreload'
set -g @plugin 'christoomey/vim-tmux-navigator'

bg="#24273a"
surface_2="#5b6078"
overlay_1="#8087a2"
mauve="#c6a0f6"
yellow="#eed49f"

set -g status-position top
set -g status-justify "absolute-centre"
set -g status-style "bg=default"
set -g status-left ""
set -ga status-left "#[bold]#{?client_prefix,#[fg=#{mauve}],#{?#{==:#{pane_mode},copy-mode},#[fg=#{yellow}],#[fg=#{overlay_1}]}} #S "

set -g status-right ""
set -ga status-right "#[bold]#[fg=#{yellow}] %H:%M #[fg=#{overlay_1}]| "
set -ga status-right "#[fg=#{yellow}]%d-%m"

setw -g pane-border-lines single

set -wg automatic-rename on
set -g automatic-rename-format "Window"

set -g message-style "bg=#{mauve} fg=#{bg} bold"

set -g window-status-separator "#[fg=#{overlay_1}]|"
set -g window-status-format '#[fg=#{overlay_1}] ⬤ #{?#{!=:#{window_name},Window},#W,}'
set -g window-status-current-format '#[fg=#{mauve},bg=default,bold] ⬤ #{?#{!=:#{window_name},Window},#W,}'

set -g pane-border-style "fg=#{surface_2}"
set -g pane-active-border-style "fg=#{mauve}"

run '$HOME/.tmux/plugins/tpm/tpm'
