# See this wiki page for more info:
# https://github.com/dylanaraps/neofetch/wiki/Customizing-Info
print_info() {
    bat ".config/neofetch/header.txt"
    prin "${blue}┌──────────────────────────────────────────────────〇"
    info "${blue}│ ${green} OS" distro
    info "${blue}│ ${green} Host" model
    info "${blue}│ ${green} Kernel" kernel
    info "${blue}│ ${green} Uptime" uptime
    info "${blue}│ ${green} Packages" packages
    info "${blue}│ ${green} Shell" shell
    info "${blue}│ ${green} DE" de
    info "${blue}│ ${green} WM" wm
    info "${blue}│ ${green} Memory" memory
    prin "${blue}└──────────────────────────────────────────────────〇"

    printf "\n                     ${reset}⬤ ${white}⬤ ${cyan}⬤ ${magenta}⬤ ${blue}⬤ ${yellow}⬤ ${green}⬤ ${red}⬤\n"
}

reset="\x1b[0m"
red="\x1b[38;2;247;118;142m"
green="\x1b[38;2;158;206;106m"
yellow="\x1b[38;2;224;175;104m"
blue="\x1b[38;2;122;162;247m"
magenta="\x1b[38;2;187;154;247m"
cyan="\x1b[38;2;125;207;255m"
white="\x1b[38;2;169;177;214m"

image_backend="off"