# See this wiki page for more info:
# https://github.com/dylanaraps/neofetch/wiki/Customizing-Info
print_info() {
    bat -p "$HOME/.config/neofetch/header.txt"
    prin "${blue}┌──────────────────────────────────────────────────〇"
    info "${blue}│ ${green} OS" distro
    info "${blue}│ ${green} Host" model
    info "${blue}│ ${green} Kernel" kernel
    info "${blue}│ ${green} Uptime" uptime
    info "${blue}│ ${green} Packages" packages
    info "${blue}│ ${green} Shell" shell
    info "${blue}│ ${green} DE" de
    info "${blue}│ ${green} WM" wm
    info "${blue}│ ${green} Memory" memory
    prin "${blue}└──────────────────────────────────────────────────〇"

    printf "\n                     ${reset}⬤ ${white}⬤ ${cyan}⬤ ${magenta}⬤ ${blue}⬤ ${yellow}⬤ ${green}⬤ ${red}⬤\n"
}

reset="\x1b[0m"
red="\x1b[38;2;255;85;85m"
green="\x1b[38;2;80;250;123m"
yellow="\x1b[38;2;241;250;140m"
blue="\x1b[38;2;102;192;255m"
magenta="\x1b[38;2;198;160;246m"
cyan="\x1b[38;2;139;233;253m"
white="\x1b[38;2;248;248;242m"

image_backend="off"