# See this wiki page for more info:
# https://github.com/dylanaraps/neofetch/wiki/Customizing-Info
print_info() {
    bat -p --paging=never ".config/neofetch/header.txt"
    prin "${blue}┌──────────────────────────────────────────────────〇"
    info "${blue}│ ${green} OS    " distro
    info "${blue}│ ${green} Host  " model
    info "${blue}│ ${green} Kernel" kernel
    info "${blue}│ ${green} Uptime" uptime
    info "${blue}│ ${green} Packages" packages
    info "${blue}│ ${green} Shell" shell
    info "${blue}│ ${green} DE" de
    info "${blue}│ ${green} WM" wm
    info "${blue}│ ${green} Memory" memory
    prin "${blue}└──────────────────────────────────────────────────〇"

    printf "\n                    ${reset}⬤ ${white}⬤ ${cyan}⬤ ${magenta}⬤ ${blue}⬤ ${yellow}⬤ ${green}⬤ ${red}⬤"
}

reset="\033[0m"
red="\033[38;2;237;135;150m"
green="\033[38;2;166;218;149m"
yellow="\033[38;2;238;212;159m"
blue="\033[38;2;138;173;244m"
magenta="\033[38;2;198;160;246m"
cyan="\033[38;2;145;215;227m"
white="\033[38;2;202;211;245m"

image_backend="off"