# See this wiki page for more info:
# https://github.com/dylanaraps/neofetch/wiki/Customizing-Info
print_info() {
    bat -p ".config/neofetch/header.txt"
    prin "${blue}┌──────────────────────────────────────────────────〇"
    info "${blue}│ ${green} OS" distro
    info "${blue}│ ${green} Host" model
    info "${blue}│ ${green} Kernel" kernel
    info "${blue}│ ${green} Uptime" uptime
    info "${blue}│ ${green} Packages" packages
    info "${blue}│ ${green} Shell" shell
    info "${blue}│ ${green} DE" de
    info "${blue}│ ${green} WM" wm
    info "${blue}│ ${green} Memory" memory
    prin "${blue}└──────────────────────────────────────────────────〇"

    printf "\n                     ${reset}⬤ ${white}⬤ ${cyan}⬤ ${magenta}⬤ ${blue}⬤ ${yellow}⬤ ${green}⬤ ${red}⬤\n"
}

reset="\x1b[0m"
red="\x1b[38;2;191;97;106m"
green="\x1b[38;2;163;190;140m"
yellow="\x1b[38;2;235;203;139m"
blue="\x1b[38;2;94;129;172m"
magenta="\x1b[38;2;180;142;173m"
cyan="\x1b[38;2;136;192;208m"
white="\x1b[38;2;236;239;244m"

image_backend="off"
