# See this wiki page for more info:
# https://github.com/dylanaraps/neofetch/wiki/Customizing-Info
print_info() {
    bat -p "$HOME/.config/neofetch/header.txt"
    prin "${blue}┌──────────────────────────────────────────────────〇"
    info "${blue}│ ${green} OS" distro
    info "${blue}│ ${green} Host" model
    info "${blue}│ ${green} Kernel" kernel
    info "${blue}│ ${green} Uptime" uptime
    info "${blue}│ ${green} Packages" packages
    info "${blue}│ ${green} Shell" shell
    info "${blue}│ ${green} DE" de
    info "${blue}│ ${green} WM" wm
    info "${blue}│ ${green} Memory" memory
    prin "${blue}└──────────────────────────────────────────────────〇"

    printf "\n                     ${reset}⬤ ${white}⬤ ${cyan}⬤ ${magenta}⬤ ${blue}⬤ ${yellow}⬤ ${green}⬤ ${red}⬤\n"
}

reset="\x1b[0m"
red="\x1b[38;2;243;139;168m"
green="\x1b[38;2;166;227;161m"
yellow="\x1b[38;2;249;226;175m"
blue="\x1b[38;2;137;180;250m"
magenta="\x1b[38;2;203;166;247m"
cyan="\x1b[38;2;137;220;235m"
white="\x1b[38;2;205;214;244m"

image_backend="off"