THEME_LOCATION="$HOME/.zthemes/cpMocha/"
export LS_COLORS="$(vivid generate catppuccin-mocha)"
export BAT_THEME="Catppuccin Mocha"
eval "$(oh-my-posh init zsh --config ${THEME_LOCATION}oh-my-posh.toml)"
cp "${THEME_LOCATION}/config.conf" "$HOME/.config/neofetch/"
cp "${THEME_LOCATION}/../header.txt" "$HOME/.config/neofetch/"
source "${THEME_LOCATION}fzf.zsh"
