# :schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 4
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[palette]
  mauve = "#8839ef"
  blue = "#1e66f5"
  green = "#40a02b"
  yellow = "#df8e1d"
  red = "#d20f39"
  subtext = "#8c8fa1"

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    background = 'transparent'
    foreground = 'p:blue'
    template = '{{ .Path }}'

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = 'p:subtext'
    background = 'transparent'
    template = ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} <cyan>{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}</>'

    [blocks.segments.properties]
      branch_icon = ''
      commit_icon = '@'
      fetch_status = true

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = 'p:yellow'
    background = 'transparent'
    template = '{{ .FormattedMs }}'

    [blocks.segments.properties]
      threshold = 1000

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground = 'p:mauve'
    background = 'transparent'
    template = '󰮺'

[transient_prompt]
  foreground = 'p:mauve'
  background = 'transparent'
  template = '󰮺 '

[secondary_prompt]
  foreground = 'p:mauve'
  background = 'transparent'
  template = '󰮺 '