command which fzf >/dev/null 2>&1 && {} || echo "FZF NOT INSTALLED"
command which bat >/dev/null 2>&1 && {} || echo "BAT NOT INSTALLED"
command which zoxide >/dev/null 2>&1 && {} || echo "ZOXIDE NOT INSTALLED"
command which oh-my-posh >/dev/null 2>&1 && {} || echo "OH-MY-POSH NOT INSTALLED"
command which neofetch >/dev/null 2>&1 && {} || echo "NEOFETCH NOT INSTALLED"